# name: demo_deploydocker
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#         id: buildx

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         id: docker_build
#         with:
#           context: .
#           file: ./Dockerfile
#           build: ${{ steps.buildx.outputs.name}}
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/ddemo_deploydocker:latest

#       - name: Notify deployment
#         run: echo ${{ steps.docker_build.outputs.digest }}


name: demo_deploydocker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo_deploydocker:latest

      - name: Notify deployment
        run: echo ${{ steps.docker_build.outputs.digest }}